backend:
  name: github
  repo: deensz/deensz.github.io
  branch: main
  base_url: https://deensz.github.io
  app_id: Iv23liRLBWhmm7wkE1Pq

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "portfolio"
    label: "Portfolio"
    files:
      - file: "data/projects.json"
        name: "projects"
        label: "Projects Data"
        fields:
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - {label: "Name/Title", name: "title", widget: "string"}
              - {label: "Short Description", name: "description", widget: "text"}
              - {label: "Image URL", name: "image", widget: "string"}
              - {label: "Key Features", name: "features", widget: "list"}
              - {label: "Tech Stack", name: "stack", widget: "list"}
